spring:
  application:
    name: pickup
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pickup}
    username: ${DB_USERNAME:pickup}
    password: ${DB_PASSWORD:dev}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
